name: audyn_prototype
description: A fully functioning prototype for the Audyn music app.

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.17
  http: ^1.2.1
  provider: ^6.1.2
  path_provider: ^2.1.2
  ffi: ^2.1.2
  shared_preferences: ^2.1.1
  uuid: ^4.0.0
  audioplayers: ^6.4.0
  flutter_media_metadata: ^1.0.0
  audio_session: ^0.1.8
  marquee: ^2.2.3
  audio_service: ^0.18.12


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true