name: audyn
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  dtorrent_parser: ^1.0.4
  dtorrent_task: ^0.4.0
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  just_audio: ^0.9.36
  audio_service: ^0.18.10
  audio_session: ^0.1.14
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.0.15
  flutter_media_metadata:
    path: lib_plugins/flutter_media_metadata/flutter_media_metadata-1.0.0+1
  image: 3.1.1
  image_extensions: 0.2.0
  marquee: ^2.2.3
  provider: ^6.1.2
  just_audio_background: ^0.0.1-beta.17
  audioplayers: ^6.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
